### PR TITLE
Animation speed 0, as quickly as possible

### PR DESCRIPTION
**Pull request by YngveE**

### CODE REVIEW

**Comment by lisbethb-met-no** [comment]
Ok, but fix code style. clang-format says:
-  for (int f10=0; f10<21; ++f10) {
+  for (int f10 = 0; f10 < 21; ++f10) {

-  float val= i/10.;
+  float val = i / 10.;

**Comment by YngveE** [comment]
Fixed!

/Yngve

Från: Lisbeth Bergholt [mailto:notifications@github.com]
Skickat: den 3 juni 2019 15:18
Till: metno/diana
Kopia: Einarsson Yngve; Author
Ämne: Re: [metno/diana] Animation speed 0, as quickly as possible (#13)


Ok, but fix code style. clang-format says:

  *   for (int f10=0; f10<21; ++f10) {

  *   for (int f10 = 0; f10 < 21; ++f10) {

  *   float val= i/10.;

  *   float val = i / 10.;

**Comment by lisbethb-met-no** [comment]
Almost :
-  float val= i / 10.;
+  float val = i / 10.;

And make it one commit

**Comment by YngveE** [comment]
Fixed!

/Yngve

Från: Lisbeth Bergholt [mailto:notifications@github.com]
Skickat: den 3 juni 2019 15:31
Till: metno/diana
Kopia: Einarsson Yngve; Author
Ämne: Re: [metno/diana] Animation speed 0, as quickly as possible (#13)


Almost :

  *   float val= i / 10.;

  *   float val = i / 10.;

And make it one commit

**Pull request merged**
