### PR TITLE
Fixed bug in plotlist

### PR DESCRIPTION
**Pull request by YngveE**

### CODE REVIEW

**Comment by lisbethb-met-no** [comment]
If plotundef is false, you will never get there.
Line 1660 will stop you
if (!plotundef && s_p == dta.stringdata.end() && f_p == dta.fdata.end())
    return;

I might be wrong, but then you must give me an example.

**Comment by YngveE** [comment]
Well, this is not true for the special case when you plot ww and the station reports no temperature.
/Yngve

Från: Lisbeth Bergholt [mailto:notifications@github.com]
Skickat: den 27 maj 2019 14:10
Till: metno/diana
Kopia: Einarsson Yngve; Author
Ämne: Re: [metno/diana] Fixed bug in plotlist (#9)


If plotundef is false, you will never get there.
Line 1660 will stop you
if (!plotundef && s_p == dta.stringdata.end() && f_p == dta.fdata.end())
return;

I might be wrong, but then you must give me an example.

**Comment by lisbethb-met-no** [comment]
Well, in that case it doesn't help to change line 1731, you must change line 1720.

**Comment by YngveE** [comment]
Of course, I was to quick. Its updated now!
/Yngve

Från: Lisbeth Bergholt [mailto:notifications@github.com]
Skickat: den 27 maj 2019 14:26
Till: metno/diana
Kopia: Einarsson Yngve; Author
Ämne: Re: [metno/diana] Fixed bug in plotlist (#9)


Well, in that case it doesn't help to change line 1731, you must change line 1720.

**Comment by lisbethb-met-no** [comment]
And this time, please test it for all the cases:
plotUndef = false
   - TTT reported
   - TTT not reported
plotUndef = true
   - TTT reported
   - TTT not reported

**Comment by YngveE** [comment]
I will do that and return with the result. Make some testcase also.

/Yngve

Från: Lisbeth Bergholt [mailto:notifications@github.com]
Skickat: den 27 maj 2019 14:37
Till: metno/diana
Kopia: Einarsson Yngve; Author
Ämne: Re: [metno/diana] Fixed bug in plotlist (#9)


And this time, please test it for all the cases:
plotUndef = false

  *   TTT reported
  *   TTT not reported
plotUndef = true
  *   TTT reported
  *   TTT not reported

**Comment by lisbethb-met-no** [comment]
It's ok now, but can you reduce it to one commit?
(git rebase -i origin/master)

**Comment by YngveE** [comment]
I will try that.

/Yngve

Från: Lisbeth Bergholt [mailto:notifications@github.com]
Skickat: den 3 juni 2019 08:51
Till: metno/diana
Kopia: Einarsson Yngve; Author
Ämne: Re: [metno/diana] Fixed bug in plotlist (#9)


It's ok now, but can you reduce it to one commit?
(git rebase -i origin/master)

**Pull request closed without merging**
